#!/usr/bin/env python3
"""Generate grapheme properties from an unpacked Unicode 17.0.0 UCD directory."""

from __future__ import annotations

import argparse
from pathlib import Path


def entries(path: Path):
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = [field.strip() for field in line.split("#", 1)[0].split(";")]
        if not fields[0]:
            continue
        bounds = fields[0].split("..")
        yield int(bounds[0], 16), int(bounds[-1], 16), fields[1:]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ucd", type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    values = [("Other", "None", False)] * 0x110000
    sources = (
        (args.ucd / "auxiliary/GraphemeBreakProperty.txt", 0),
        (args.ucd / "DerivedCoreProperties.txt", 1),
        (args.ucd / "emoji/emoji-data.txt", 2),
    )
    for path, field in sources:
        for first, last, properties in entries(path):
            if field == 1 and properties[0] != "InCB":
                continue
            if field == 2 and properties[0] != "Extended_Pictographic":
                continue
            value = True if field == 2 else properties[-1].replace("Regional_Indicator", "RegionalIndicator")
            for codepoint in range(first, last + 1):
                updated = list(values[codepoint])
                updated[field] = value
                values[codepoint] = tuple(updated)
    lines = [
        "// Generated by tools/generate_unicode_grapheme_data.py from Unicode 17.0.0.",
        "// Copyright Unicode, Inc. See vendor/unicode/LICENSE.",
        "constexpr GraphemeRange kGraphemeRanges[] = {",
    ]
    first = 0
    while first < len(values):
        last = first
        while last + 1 < len(values) and values[last + 1] == values[first]:
            last += 1
        breaking, conjunct, pictographic = values[first]
        if values[first] != ("Other", "None", False):
            lines.append(
                f"    {{0x{first:04x}, 0x{last:04x}, "
                f"{{GraphemeBreak::{breaking}, IndicConjunct::{conjunct}, {str(pictographic).lower()}}}}},"
            )
        first = last + 1
    lines.append("};")
    (root / "vendor/unicode/grapheme_data.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
